# lovelace_gen

#=====================
#=== GENERAL SETTINGS
#=====================
type: entities
entities:

  - type: custom:hui-element
    card_type: vertical-stack
    cards:

      #=== IRRIGATION MASTER CONTROL AND TESTING MODE
      - type: horizontal-stack
        cards:

          #=== IRRIGATION MASTER CONTROL SWITCH
          - !include
            - ../item_settings_select_button_with_icon.yaml
            - entity: input_boolean.irrigation_master_control_switch
              on_name: "Sistema ON"
              off_name: "Sistema OFF"

          #=== IRRIGATION REMOTE CONTROL
          - !include
            - ../item_settings_select_button_with_icon.yaml
            - entity: input_boolean.irrigation_remote_control
              on_name: "Controllo Remoto ON"
              off_name: "Controllo Remoto OFF"
              off_icon: mdi:remote-off

      #=== IRRIGATION TESTING MODE AND WARNING
      - type: horizontal-stack
        cards:

          #=== IRRIGATION TESTING MODE
          - !include
            - ../item_settings_select_button_with_icon.yaml
            - entity: input_boolean.irrigation_testing_mode
              on_name: "Modalita Test ON"
              off_name: "Modalita Test  OFF"

          #=== TESTING MODE WARNING
          - !include
              - item_settings_warning.yaml
              - entity: input_boolean.irrigation_testing_modeForecast High Temperature
                name: 'Avvertimento! La modalità di test converte i tempi<br>di esecuzione da minuti a secondi'

      #=== IRRIGATION LOGGING
      - type: horizontal-stack
        cards:
          - !include
            - ../item_settings_check_box_with_entity_icon.yaml
            - entity: input_boolean.logging_irrigation
              name: Logging
              on_icon: mdi:notebook-check
              off_icon: mdi:notebook-remove-outline

          - !include
            - ../item_settings_check_box_with_entity_icon.yaml
            - entity: input_boolean.logging_irrigation_clear_log
              name: Cancella registro a mezzanotte
              on_icon: mdi:notebook-outline
              off_icon: mdi:notebook
              double_tap_action: call-service
              double_tap_action_service: shell_command.logging_my_log_irrigation_clear

      #=== NOTIFY USERS
      - !include item_settings_notify_users.yaml

      #=== EDIT USER NAMES
      - !include item_settings_edit_user_names.yaml

      #-------------------------
      - type: custom:hui-element
        row_type: divider
      #-------------------------

      #=== UI FONT
      - !include item_settings_ui_font.yaml

      #=== WEATHER SENSORS
      - !include item_settings_weather_sensors.yaml

      #=== NUMBER OF ZONES
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_number_of_zones
            name: Numero di Zone

      #=== PAUSE BETWEEN ZONES
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_pause_between_zones_in_seconds
            name: Pausa tra Zone

      #=== MINIMUM DURATION WHEN USING WEATHER ADJUSTMENTS
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_weather_adjusted_minimum_duration_in_seconds
            name: Tempo Minimo per Zona
            label: Quando si utilizzano le regolazioni meteorologiche

      #=== MAXIMUM DURATION WHEN USING WEATHER ADJUSTMENTS
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_weather_adjusted_maximum_duration_in_minutes
            name: Tempo massimo per gestire una zona
            label: Quando si utilizzano le regolazioni meteorologiche

      #-------------------------
      - type: custom:hui-element
        row_type: divider
      #-------------------------

      #=== CONTROLLER WIFI SIGNAL
      - type: custom:config-template-card
        variables:
          CONTROLLER: states['input_text.irrigation_external_sensor_controller_wifi'].state
        entities:
          - input_text.irrigation_external_sensor_controller_wifi
          - ${states['input_text.irrigation_external_sensor_controller_wifi'].state}
          - input_text.irrigation_ui_font_family
        card:
          !include
            - item_settings_controller_wifi_signal.yaml
            - entity: "${CONTROLLER}"
              name: Controllo irrigazione

      #=== TESTING MODE WARNING
      - !include
          - item_settings_warning.yaml
          - entity: input_boolean.irrigation_disable_switches
            name: 'Avvertimento! Interruttori disabilitati'

