# lovelace_gen

#======================
#=== RAINFALL SETTINGS
#======================
type: entities
entities:

  - type: custom:hui-element
    card_type: vertical-stack
    cards:

      #=== GENERAL RAINFALL SETTINGS
      - type: custom:button-card  
        show_icon: false
        name: IMPOSTAZIONI PIOGGIA
        tap_action:
          action: none

        #=== ANCHOR STYLES FOR ALL HEADINGS ON THE PAGE
        styles: &title_style
          card:
            - color: var(--secondary-text-color)
            - border-radius: 0em
            - background: none
            - padding-top: 0em
            - padding-bottom: 0em
            - padding-left: 0.5em
            - font-family: >
                [[[
                  return states['input_text.irrigation_ui_font_family'].state
                ]]]
            - font-size: 18px
          name:
            - justify-self: start
            - border-left: 3px solid var(--accent-color)
            - padding-left: 0.5em

      #=== NUMBER OF DAYS HISTORY
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_days_of_rainfall_history_used
            name: Numero di giorni di cronologia da utilizzare
            label: (da 0 a 4) Se zero viene utilizzata solo la pioggia odierna
            round: 0

      #=== RAINFALL THRESHOLD
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_rainfall_threshold
            name: Soglia pioggia
            label: Se questa soglia viene raggiunta non avviene alcuna irrigazione

      #=== IGNORE SCHEDULES IF RAINING
      - !include
        - ../item_settings_check_box_with_entity_icon.yaml
        - entity: input_boolean.irrigation_ignore_schedule_if_raining
          columns: 1
          on_icon: mdi:calendar-check-outline
          off_icon: mdi:calendar-remove-outline

      #-------------------------
      - type: custom:hui-element
        row_type: divider
      #-------------------------

      - type: custom:hui-element
        card_type: horizontal-stack
        cards:

          #=== RAINFALL INCLUDED IN CALCULATIONS
          - type: custom:button-card  
            show_icon: false
            name: PIOGGIA INCLUSA NEI CALCOLI
            tap_action:
              action: none
            styles: *title_style

          #=== EDIT BUTTON FOR RAINFALL INCLUDED IN CALCULATIONS
          - type: custom:button-card
            icon: mdi:square-edit-outline
            styles:
              card:
                - width: 4em
                - padding-right: 0.5em

            #=== ALLOW EDITING OF PERCENTAGES
            tap_action:
              action: fire-dom-event
              browser_mod:
                service: browser_mod.popup
                data:
                  title: Precipitazioni incluse nei calcoli
                  content:
                    type: entities
                    entities:
                      - entity: input_number.irrigation_rainfall_percentage_1
                      - entity: input_number.irrigation_rainfall_percentage_2
                      - entity: input_number.irrigation_rainfall_percentage_3
                      - entity: input_number.irrigation_rainfall_percentage_4
                    card_mod:
                      style: >
                        ha-card {
                          font-family: {% raw %}{{ states('input_text.irrigation_ui_font_family') }}{% endraw %};
                          }
                  #=== Style needed for pop-up title
                  style:
                    $: |
                      .mdc-dialog .mdc-dialog__container .mdc-dialog__surface {
                          font-family: {% raw %}{{ states('input_text.irrigation_ui_font_family') }}{% endraw %};
                        }

      #=== YESTERDAY
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_rainfall_percentage_1
            name: Ieri
            tap_action: none
            padding: 0.3em 0em 0em 0em

      #=== TWO DAYS AGO
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_rainfall_percentage_2
            name: Due giorni fa
            tap_action: none

      #=== THREE DAYS AGO
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_rainfall_percentage_3
            name: Tre giorni fa
            tap_action: none

      #=== FOUR DAYS AGO
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_rainfall_percentage_4
            tap_action: none
            name: Quattro giorni fa
            padding: 0em 0em 0.3em 0em

      #-------------------------
      - type: custom:hui-element
        row_type: divider
      #-------------------------

      #=== RAINFALL DATA
      - type: custom:button-card  
        show_icon: false
        name: DATI PIOGGIA
        tap_action:
          action: none
        styles: *title_style

      #=== MULTIPLIER USED IN CALCULATIONS
      - !include
          - ../item_settings_multiplier_line.yaml
          - entity: input_number.irrigation_rainfall_multiplier
            name: "Moltiplicatore Corrente ( ℹ️ )"
            label: Calcolato in base alle precipitazioni e alla soglia

      #=== RAINFALL TODAY
      - !include
          - ../item_settings_line.yaml
          - entity: sensor.irrigation_sensor_rainfall_today
            name: Pioggia Oggi
            icon: mdi:weather-rainy
            round: 1
            tap_action: none

      #=== RAINFALL YESTERDAY
      - !include
          - ../item_settings_line.yaml
          - entity: sensor.irrigation_sensor_rainfall_yesterday
            name: Ieri
            icon: mdi:weather-rainy
            round: 1
            tap_action: none
            display_condition: "[[[ return states['input_number.irrigation_days_of_rainfall_history_used'].state < 1 ? 'none' : 'unset' ]]]"

      #=== RAINFALL TWO DAYS AGO
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_rainfall_2
            name: Due giorni fa
            round: 1
            tap_action: none
            display_condition: "[[[ return states['input_number.irrigation_days_of_rainfall_history_used'].state < 2 ? 'none' : 'unset' ]]]"

      #=== RAINFALL THREE DAYS AGO
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_rainfall_3
            name: Tre giorni fa
            round: 1
            tap_action: none
            display_condition: "[[[ return states['input_number.irrigation_days_of_rainfall_history_used'].state < 3 ? 'none' : 'unset' ]]]"

      #=== RAINFALL FOUR DAYS AGO
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_rainfall_4
            name: Quattro giorni fa
            round: 1
            tap_action: none
            display_condition: "[[[ return states['input_number.irrigation_days_of_rainfall_history_used'].state < 4 ? 'none' : 'unset' ]]]"
            padding: 0em 0em 0.3em 0em

      #=== SMARTWEATHER STATIONS USED
      - !include item_settings_smartweather_stations_used.yaml

      #-------------------------
      - type: custom:hui-element
        row_type: divider
      #-------------------------

      #=== FORECAST RAIN VS. ACTUAL RAIN
      - type: custom:button-card  
        show_icon: false
        name:  PIOGGIA - <font color=IndianRed>Previsione</font> vs. <font color=SteelBlue>Attuale</font>
        tap_action:
          action: none
        styles: *title_style

      #=== FORECAST VS. ACTUAL RIAN GRAPH
      - !include item_settings_rainfall_graph.yaml

card_mod:
  style: >
    ha-card {
      box-shadow: none;
    }
